### ISSUE TITLE
@abstract 'xxx.mcss'的时候路径找不到

### ISSUE THREAD

**Issue by Froguard** [zjzhome/mcss-loader#1]
如题：
//js使用

```
 require("a.mcss");
```

//a.mcss文件中，行首部分为

```
 @abstract ‘b.mcss’；
```

//结果提示：

```
 ERROR in ./~/css-loader!./~/mcss-loader!./mcss/a.mcss
 Module build failed: SyntaxError: b.mcss FILE NOT FOUND
 at null.<anonymous> (d:\app\node_modules\mcss\lib\parser.js:1354:27)
 at extend.reject (d:\app\node_modules\mcss\lib\helper\promise.js:63:10)
 at ReadFileContext.callback (d:\app\node_modules\mcss\lib\helper\io.js:65:28)
 at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:303:13)
```

**Module build failed: SyntaxError: b.mcss FILE NOT FOUND**

但其实文件时存在的，我用mcss指令直接运行编译，则不会报错，，正常编译

```
mcss -c mcss/mcss.json
```

btw:文件比较简单，自信不会在语法上出问题...  
点解？怎么破？

**Comment by sweet-zone** [comment]
我刚才试了一下, 并没有出现这个问题, 能贴一下完整的代码么...
